routes/web.php
<?php

  Route::get('/', 'TestController@welcome');

  Auth::routes();

  Route::get('/search','SearchController@show');
  Route::get('/products/json','SearchController@data');

  Route::get('/home', 'HomeController@index')->name('home');
  Route::get('/products/{id}','ProductController@show');
  Route::get('/categories/{category}','CategoryController@show');




  Route::post('/cart','CartDetailController@store');
  Route::delete('/cart','CartDetailController@destroy');

  Route::post('/order','CartController@update');

  Route::middleware(['auth','admin'])->prefix('admin')->namespace('Admin')->group(function(){
    Route::get('/products','ProductController@index'); // listado
    Route::get('/products/create','ProductController@create'); // formmulario
    Route::post('/products','ProductController@store'); //  registrar
    Route::get('/products/{id}/edit','ProductController@edit'); // formulario edición7
    Route::post('/products/{id}/edit','ProductController@update'); //  actualizar
    Route::delete('/products/{id}','ProductController@destroy'); //form eliminar

    Route::get('/products/{id}/images','ImageController@index'); //listado
    Route::post('/products/{id}/images','ImageController@store'); //  registrar
    Route::delete('/products/{id}/images','ImageController@destroy'); //form eliminar
    Route::get('/products/{id}/images/select/{image}','ImageController@select'); //destacar imagen


    Route::get('/categories','CategoryController@index'); // listado
    Route::get('/categories/create','CategoryController@create'); // formmulario
    Route::post('/categories','CategoryController@store'); //  registrar
    Route::get('/categories/{category}/edit','CategoryController@edit'); // formulario edición7
    Route::post('/categories/{category}/edit','CategoryController@update'); //  actualizar
    Route::delete('/categories/{id}','CategoryController@destroy'); //form eliminar


  });

    Route::get('/logout', function () {
        Auth::logout();
        return redirect('login');
    })->name('auth_logout');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/*use App\ProductImage;*/

class Product extends Model
{
    //product->category
    public function category()
    {
    	return $this->belongsto(Category::class);
    }

    // $product->images
    public function images()
    {
    	return $this->hasMany(ProductImage::class);

    }

	public function getFeaturedImageUrlAttribute()
	{
		$featuredImage = $this->images()->where('featured',true)->first();

		if (!$featuredImage)
			$featuredImage = $this->images()->first();

		if ($featuredImage) {
			return $featuredImage->url;
		}

		//default
		return '/images/default.gif';
	}

  public function getCategoryNameAttribute()
  {
    if ($this->category)
      return $this->category->name;

    return 'General';
  }


}

app/Http/Controllers/SearchController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Product;

class SearchController extends Controller
{
    public function show(Request $request)
    {
      $query = $request->input('query');
      $products = Product::where('name','like',"%$query%")->paginate(5);

      if ($products->count()==1){
        $id = $products->first()->id;
        return redirect("products/$id"); //usar comillas dobles equivale a usar la concatenacion 'products/' .$id
      }

      return view('search.show')->with(compact('products','query'));
    }

    public function data()
    {
      $products = Product::pluck('name');
      return $products;
    }
}

resources/views/search/show.blade.php
@extends('layouts.app')

@section('title','Resultados de búsqueda')

@section('body-class','profile-page')

@section('styles')
  <style media="screen">
    .team {
      padding: 50px;
    }
    .team .row .col-md-4{
        margin-bottom: 5em;
    }
    .team .row {
        display: -webkit-box;
        display: -webkit-flex;
        display: -ms-flexbox;
        display: flex;
        flex-wrap: wrap;
    }
    .team .row > [class*='col-'] {
        display: flex;
        flex-direction: column;
    }

  </style>

@endsection

@section('content')

<div class="header header-filter" style="background-image: url('/img/examples/city.jpg');"></div>

<div class="main main-raised">
    <div class="profile-content">
        <div class="container">
            <div class="row">
                <div class="profile">
                    <div class="avatar">
                        <img src="/img/search.jpg" alt="Imagen de una lupa que representa a la página de resultados" class="img-circle img-responsive img-raised">
                    </div>

                    <div class="name">
                        <h3 class="title">Resultados de búsqueda</h3>
                    </div>
                </div>
            </div>
            <div class="description text-center">
                <p>Se encontraron {{ $products->count() }} resultados para el término {{ $query }}  </p>
            </div>

            @if (session('notification'))
<!--            <div class="alert alert-success">
                    {{ session('notification') }}
                </div> -->
                <div class="alert alert-success">
                    <div class="container-fluid">
                      <div class="alert-icon">
                        <i class="material-icons">check</i>
                      </div>
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true"><i class="material-icons">clear</i></span>
                      </button>
                      <b> Notificación: </b>{{ session('notification') }}
                    </div>
                </div>
            @endif

            <div class="team text-center">
                <div class="row">
                    @foreach ($products as $product)
                    <div class="col-md-4">
                        <div class="team-player">
                            <img src="{{ $product->featured_image_url }}" alt="Thumbnail Image" class="img-raised img-circle">
                            <h4 class="title">
                                <a href="{{ url('/products/'.$product->id) }}">{{ $product->name }}</a>
                            </h4>
                            <p class="description">{{ $product->description }}</p>
                        </div>
                    </div>
                    @endforeach
                </div>
                <div class="text-center">
                    {{ $products->links() }}
                </div>
            </div>
        </div>
    </div>
</div>

@include('includes.footer')
@endsection