routes/web.php
<?php

  Route::get('/', 'TestController@welcome');

  Auth::routes();

  Route::get('/search','SearchController@show');
  Route::get('/products/json','SearchController@data');

  Route::get('/home', 'HomeController@index')->name('home');
  Route::get('/products/{id}','ProductController@show');
  Route::get('/categories/{category}','CategoryController@show');




  Route::post('/cart','CartDetailController@store');
  Route::delete('/cart','CartDetailController@destroy');

  Route::post('/order','CartController@update');

  Route::middleware(['auth','admin'])->prefix('admin')->namespace('Admin')->group(function(){
    Route::get('/products','ProductController@index'); // listado
    Route::get('/products/create','ProductController@create'); // formmulario
    Route::post('/products','ProductController@store'); //  registrar
    Route::get('/products/{id}/edit','ProductController@edit'); // formulario edición7
    Route::post('/products/{id}/edit','ProductController@update'); //  actualizar
    Route::delete('/products/{id}','ProductController@destroy'); //form eliminar

    Route::get('/products/{id}/images','ImageController@index'); //listado
    Route::post('/products/{id}/images','ImageController@store'); //  registrar
    Route::delete('/products/{id}/images','ImageController@destroy'); //form eliminar
    Route::get('/products/{id}/images/select/{image}','ImageController@select'); //destacar imagen


    Route::get('/categories','CategoryController@index'); // listado
    Route::get('/categories/create','CategoryController@create'); // formmulario
    Route::post('/categories','CategoryController@store'); //  registrar
    Route::get('/categories/{category}/edit','CategoryController@edit'); // formulario edición7
    Route::post('/categories/{category}/edit','CategoryController@update'); //  actualizar
    Route::delete('/categories/{id}','CategoryController@destroy'); //form eliminar


  });

    Route::get('/logout', function () {
        Auth::logout();
        return redirect('login');
    })->name('auth_logout');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/*use App\ProductImage;*/

class Product extends Model
{
    //product->category
    public function category()
    {
    	return $this->belongsto(Category::class);
    }

    // $product->images
    public function images()
    {
    	return $this->hasMany(ProductImage::class);

    }

	public function getFeaturedImageUrlAttribute()
	{
		$featuredImage = $this->images()->where('featured',true)->first();

		if (!$featuredImage)
			$featuredImage = $this->images()->first();

		if ($featuredImage) {
			return $featuredImage->url;
		}

		//default
		return '/images/default.gif';
	}

  public function getCategoryNameAttribute()
  {
    if ($this->category)
      return $this->category->name;

    return 'General';
  }


}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;

use Illuminate\Http\Request;
use App\Product;
use App\Category;
use App\ProductImage;

class ProductController extends Controller
{
    public function index()
    {
    	$products = Product::paginate(10);
		return view('admin.products.index')->with(compact('products')); //listado
    }
    public function create()
    {
      $categories = Category::orderBy('name')->get();
      return view('admin.products.create')->with(compact('categories')); //formulario de registro
    }
    public function store(Request $request)
    {
      /*dd($request->all());*/

      // validar
      $messages=[
        'name.required' => 'Es necesario ingresar un nombre para el producto.',
        'name.min' => 'El nombre del producto debe tener al menos 3 caracteres.',
        'description.required' => 'La descripción corta es obligatoria.',
        'description.max' => 'La descripción corta solo admite hasta 200 caracteres.',
        'price.required'=>'Es obligatorio definir un precio para el producto.',
        'price.numeric'=>'Ingrese un precio valido.',
        'price.min'=>'No se admiten precios negativos.'
      ];
      $rules = [
        'name' => 'required|min:3',
        'description' => 'required|max:200',
        'price' => 'required|numeric|min:0'
      ];
      $this->validate($request, $rules,$messages);

      //registrar el nuevo producto en la bd
    	$product = new Product();
    	$product->name = $request->input('name');
    	$product->description = $request->input('description');
    	$product->price = $request->input('price');
    	$product->long_description = $request->input('long_description');
      $product->category_id = $request->category_id;
    	$product->save(); /*INSERT*/

    	return redirect('/admin/products');

    }
	public function edit($id)
    {
    	/*return "Mostrar aqui el form de edición para el producto con id $id";	*/
      $categories = Category::orderBy('name')->get();
      $product = Product::find($id);
 		  return view('admin.products.edit')->with(compact('product','categories')); //formulario de edición
    }
    public function update(Request $request, $id) //actualizacion
    {
      // validar
      $messages=[
        'name.required' => 'Es necesario ingresar un nombre para el producto.',
        'name.min' => 'El nombre del producto debe tener al menos 3 caracteres.',
        'description.required' => 'La descripción corta es obligatoria.',
        'description.max' => 'La descripción corta solo admite hasta 200 caracteres.',
        'price.required'=>'Es obligatorio definir un precio para el producto.',
        'price.numeric'=>'Ingrese un precio valido.',
        'price.min'=>'No se admiten precios negativos.'
      ];
      $rules = [
        'name' => 'required|min:3',
        'description' => 'required|max:200',
        'price' => 'required|numeric|min:0'
      ];
      $this->validate($request, $rules,$messages);
    	//registrar el nuevo producto en la bd
    	/*dd($request->all());*/
    	$product = Product::find($id);
    	$product->name = $request->input('name');
    	$product->description = $request->input('description');
    	$product->price = $request->input('price');
    	$product->long_description = $request->input('long_description');
      $product->category_id = $request->category_id;
    	$product->save(); /*UPDATE*/

    	return redirect('/admin/products');
    }
    public function destroy($id) //actualizacion
    {

      ProductImage::where('product_id', $id)->delete();

    	$product = Product::find($id);
        $product->delete(); /*DELETE*/
        // $product->foreign('product_id')->references('id')->on('product_images')->onDelete('cascade');

    	return back();
    }

    public function show($id)
    {
        $product = Product::find($id); //buscamos el producto
        $images = $product->images; //traemos las images del producto

        $imagesLeft = Collect(); //creamos una coleccion de imagenes para la parte izq
        $imagesRight = Collect(); //creamos una coleccion de imagenes para la parte der

        foreach ($images as $key => $image) {
            if($key%2==0)
                $imagesLeft->push($image);
            else
                $imagesRight->push($image);

        }

        return view('products.show')->with(compact('product','imagesLeft','imagesRight','notification')); //pasamos a la vista
    }

}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Product;
use App\Category;
use App\ProductImage;

class ProductController extends Controller
{
    public function index()
    {
    	$products = Product::paginate(10);
		return view('admin.products.index')->with(compact('products')); //listado
    }
    public function create()
    {
      return view('admin.products.create'); //formulario de registro
    }
    public function store(Request $request)
    {
      /*dd($request->all());*/

      // validar
      $messages=[
        'name.required' => 'Es necesario ingresar un nombre para el producto.',
        'name.min' => 'El nombre del producto debe tener al menos 3 caracteres.',
        'description.required' => 'La descripción corta es obligatoria.',
        'description.max' => 'La descripción corta solo admite hasta 200 caracteres.',
        'price.required'=>'Es obligatorio definir un precio para el producto.',
        'price.numeric'=>'Ingrese un precio valido.',
        'price.min'=>'No se admiten precios negativos.'
      ];
      $rules = [
        'name' => 'required|min:3',
        'description' => 'required|max:200',
        'price' => 'required|numeric|min:0'
      ];
      $this->validate($request, $rules,$messages);

      //registrar el nuevo producto en la bd
    	$product = new Product();
    	$product->name = $request->input('name');
    	$product->description = $request->input('description');
    	$product->price = $request->input('price');
    	$product->long_description = $request->input('long_description');
    	$product->save(); /*INSERT*/

    	return redirect('/admin/products');

    }
	public function edit($id)
    {
    	/*return "Mostrar aqui el form de edición para el producto con id $id";	*/
    	$product = Product::find($id);
 		return view('admin.products.edit')->with(compact('product')); //formulario de edición
    }
    public function update(Request $request, $id) //actualizacion
    {
      // validar
      $messages=[
        'name.required' => 'Es necesario ingresar un nombre para el producto.',
        'name.min' => 'El nombre del producto debe tener al menos 3 caracteres.',
        'description.required' => 'La descripción corta es obligatoria.',
        'description.max' => 'La descripción corta solo admite hasta 200 caracteres.',
        'price.required'=>'Es obligatorio definir un precio para el producto.',
        'price.numeric'=>'Ingrese un precio valido.',
        'price.min'=>'No se admiten precios negativos.'
      ];
      $rules = [
        'name' => 'required|min:3',
        'description' => 'required|max:200',
        'price' => 'required|numeric|min:0'
      ];
      $this->validate($request, $rules,$messages);
    	//registrar el nuevo producto en la bd
    	/*dd($request->all());*/
    	$product = Product::find($id);
    	$product->name = $request->input('name');
    	$product->description = $request->input('description');
    	$product->price = $request->input('price');
    	$product->long_description = $request->input('long_description');
    	$product->save(); /*UPDATE*/

    	return redirect('/admin/products');
    }
    public function destroy($id) //actualizacion
    {

      ProductImage::where('product_id', $id)->delete();

    	$product = Product::find($id);
        $product->delete(); /*DELETE*/
        // $product->foreign('product_id')->references('id')->on('product_images')->onDelete('cascade');

    	return back();
    }

    public function show($id)
    {
        $product = Product::find($id); //buscamos el producto
        $images = $product->images; //traemos las images del producto

        $imagesLeft = Collect(); //creamos una coleccion de imagenes para la parte izq
        $imagesRight = Collect(); //creamos una coleccion de imagenes para la parte der

        foreach ($images as $key => $image) {
            if($key%2==0)
                $imagesLeft->push($image);
            else
                $imagesRight->push($image);

        }

        return view('products.show')->with(compact('product','imagesLeft','imagesRight')); //pasamos a la vista
    }

}

resources/views/admin/products/create.blade.php
@extends('layouts.app')

@section('title','Bienvenido a App Shop')

@section('body-class','product-page')

@section('content')
<div class="header header-filter" style="background-image: url('https://images.unsplash.com/photo-1423655156442-ccc11daa4e99?crop=entropy&dpr=2&fit=crop&fm=jpg&h=750&ixjsv=2.1.0&ixlib=rb-0.3.5&q=50&w=1450');">

</div>

<div class="main main-raised">
    <div class="container">
        <div class="section">
            <h2 class="title" align="center">Registrar nuevo producto</h2>

            @if ($errors->any())
              <div class="alert alert-danger">
                <u>
                  @foreach ($errors->all() as $error)
                      <li>{{ $error }}</li>
                  @endforeach
                </u>
              </div>
            @endif

            <form method="post" action="{{ url('/admin/products') }}">
                {{ csrf_field() }}

                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group label-floating">
                            <label class="control-label">Nombre del producto</label>
                            <input type="text" class="form-control" name="name" value="{{ old('name') }}">
                        </div>
                    </div>

                    <div class="col-sm-6">
                        <div class="form-group label-floating">
                            <label class="control-label">Precio del producto</label>
                            <input type="number" class="form-control" name="price" value="{{ old('price') }}">
                        </div>
                    </div>
                </div>
                <div class="row">
                  <div class="col-sm-6">
                    <div class="form-group label-floating">
                        <label class="control-label">Descripción corta</label>
                        <input type="text" class="form-control" name="description" value="{{ old('description') }}">
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <div class="form-group label-floating">
                        <label class="control-label">Categoría del producto</label>
                        <select class="form-control" name="category_id">
                          <option value="0">General</option>
                          @foreach ($categories as $category)
                            <option value="{{ $category->id }}">{{ $category->name }}</option>
                          @endforeach
                        </select>
                    </div>
                  </div>
                </div>
                <textarea class="form-control" placeholder="Descripción extensa del producto" rows="5" name="long_description">{{ old('long_description') }}</textarea>


                <button class="btn btn-primary btn-just-icon pull-right">
                    <i class="material-icons">save</i>Registrar producto
                </button>
                <a href="{{ url('/admin/products') }}" class="btn btn-default pull-right">Cancelar</a>
            </form>

        </div>
    </div>
</div>

@include('includes.footer')
@endsection

resources/views/admin/products/edit.blade.php
@extends('layouts.app')

@section('title','Bienvenido a App Shop')

@section('body-class','product-page')

@section('content')
<div class="header header-filter" style="background-image: url('https://images.unsplash.com/photo-1423655156442-ccc11daa4e99?crop=entropy&dpr=2&fit=crop&fm=jpg&h=750&ixjsv=2.1.0&ixlib=rb-0.3.5&q=50&w=1450');">

</div>

<div class="main main-raised">
    <div class="container">
        <div class="section">
            <h2 class="title" align="center">Editar producto seleccionado</h2>

            @if ($errors->any())
              <div class="alert alert-danger">
                <u>
                  @foreach ($errors->all() as $error)
                      <li>{{ $error }}</li>
                  @endforeach
                </u>
              </div>
            @endif

            <form method="post" action="{{ url('/admin/products/'.$product->id.'/edit') }}">
                {{ csrf_field() }}

                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group label-floating">
                            <label class="control-label">Nombre del producto</label>
                            <input type="text" class="form-control" name="name" value="{{ old('name', $product->name) }}">
                        </div>
                    </div>

                    <div class="col-sm-6">
                        <div class="form-group label-floating">
                            <label class="control-label">Precio del producto</label>
                            <input type="number" step="0.01" class="form-control" name="price" value="{{ old('price', $product->price) }}">
                        </div>
                    </div>
                </div>
                <div class="row">
                  <div class="col-sm-6">
                    <div class="form-group label-floating">
                        <label class="control-label">Descripción corta</label>
                        <input type="text" class="form-control" name="description" value="{{ old('description') }}">
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <div class="form-group label-floating">
                        <label class="control-label">Categoría del producto</label>
                        <select class="form-control" name="category_id">
                          <option value="0">General</option>
                          @foreach ($categories as $category)
                            <option value="{{ $category->id }}" @if($category->id == old('category_id',$product->category_id)) selected @endif>
                              {{ $category->name }}
                            </option>
                          @endforeach
                        </select>
                    </div>
                  </div>
                </div>
                <textarea class="form-control" placeholder="Descripción extensa del producto" rows="5" name="long_description">{{ old('long_description', $product->long_description) }}"</textarea>


                <button class="btn btn-primary pull-right">
                    <i class="material-icons">save</i>Guardar cambios
                </button>
                <a href="{{ url('/admin/products') }}" class="btn btn-default pull-right">Cancelar</a>

            </form>

        </div>
    </div>
</div>

@include('includes.footer')
@endsection

resources/views/admin/products/index.blade.php
@extends('layouts.app')

@section('title','Listado de Productos')

@section('body-class','product-page')

@section('content')
<div class="header header-filter" style="background-image: url('/img/productos-agricolas-mexico.jpg');"></div>


<div class="main main-raised">
    <div class="container">
        <div class="section text-center">
            <h2 class="title">Listado de productos</h2>

            <div class="team">
                <div class="row">

                    <a href="{{ url('/admin/products/create') }}" class='btn btn-primary btn-round pull-right'>Nuevo producto</a>

                    <table class="table">
                        <thead>
                            <tr>
                                <th class="text-justify">#</th>
                                <th class="col-md-2 text-center">Nombre</th>
                                <th class="col-md-4 text-center">Descripción</th>
                                <th class="text-center">Categoría</th>
                                <th class="text-right">Precio</th>
                                <th class="text-right">Opciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($products as $product)
                            <tr>
                                <td class="text-center">{{ $product->id }}</td>
                                <td class="col-md-2 text-justify">{{ $product->name }}</td>
                                <td class="text-justify">{{ $product->description }}</td>
                                <td class="text-center">{{ $product->category_name }}</td>
                                <td class="text-right">&dollar; {{ $product->price }}</td>
                                <td class="td-actions text-right">

                                    <form class="" action="{{ url('/admin/products/'.$product->id) }}" method="post">
                                      {{ csrf_field() }}
                                      {{ method_field('DELETE') }}
                                      <a href="{{ url('/products/'.$product->id)}}" rel="tooltip" title="Ver producto" class="btn btn-info btn-simple btn-xs"  target="_blank">
                                          <i class="fa fa-info"></i>
                                      </a>
                                      <a href="{{ url('/admin/products/'.$product->id.'/edit') }}" rel="tooltip" title="Editar Producto" class="btn btn-success btn-simple btn-xs">
                                          <i class="fa fa-edit"></i>
                                      </a>
                                      <a href="{{ url('/admin/products/'.$product->id.'/images') }}" rel="tooltip" title="Imágenes del producto" class="btn btn-warning btn-simple btn-xs">
                                          <i class="fa fa-image"></i>
                                      </a>
                                      <button type="submit" rel="tooltip" title="Eliminar" class="btn btn-danger btn-simple btn-xs">
                                          <i class="fa fa-times"></i>
                                      </button>
                                    </form>
                                    <!-- <a href="{{ url('/admin/products/'.$product->id.'/delete') }}" rel="tooltip" title="Eliminar" class="btn btn-danger btn-simple btn-xs">
                                        <i class="fa fa-times"></i>
                                    </a> -->
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                    {{ $products->links() }}
                </div>
            </div>

        </div>
    </div>

</div>

@include('includes.footer')
@endsection